apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-backstage-app
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental

---

  apiVersion: backstage.io/v1alpha1
  kind: Component
  metadata:
    name: a-python-library
    description: A Python Library
    annotations:
        backstage.io/techdocs-ref: dir:.
        github.com/project-slug: pep8speaks-org/pep8speaks
    tags:
        - python
    links:
        - url: https://admin.example-org.com
          title: Admin Dashboard
          icon: dashboard
          type: admin-dashboard
  spec:
    type: service
    lifecycle: production
    owner: idpadmins
    system: project-x
